[changelog]
header = """
<!---
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
-->

# Changelog
"""
body = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}
{% if version %}
  ## [{{ version | trim_start_matches(pat="v") }}]({{ self::remote_url() }}/tree/{{ version | trim_start_matches(pat="v")}}) - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}
  ## [unreleased]
{% endif %}
### What's changed
{% for group, commits in commits | filter(attribute="merge_commit", value=false) | group_by(attribute="group") %}
  #### {{ group }}
  {% for commit in commits %}
    {%- if commit.remote.pr_title -%}
      {% set commit_message = commit.remote.pr_title | lower | trim %}
    {%- else -%}
      {% set commit_message = commit.message | lower | trim %}
    {%- endif -%}
    * {{ commit_message | split(pat="\n") | first | trim }}\
      {% if commit.remote.username %} by **@{{ commit.remote.username }}**{% endif %}\
      {% if commit.remote.pr_number %} in [#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }}){% endif %}    
  {% endfor -%}
{% endfor %}
{% if version %}
  {%- if previous.version -%}
    **Full Changelog**: {{ self::remote_url() }}/compare/{{ previous.version }}...{{ version }}
  {% endif -%}
{% endif %}
"""
footer = """
<!-- generated by git-cliff -->
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
commit_parsers = [
  { message = "$^", skip = true },
  { field = "remote.username", pattern = "invalid-email-address", skip = true },
  { field = "remote.pr_title", pattern = "feat:", group = "<!-- 0 -->ğŸš€ Features" },
  { field = "remote.pr_title", pattern = "fix:", group = "<!-- 1 -->ğŸ› Bug Fixes" },
  { field = "remote.pr_title", pattern = "doc:", group = "<!-- 3 -->ğŸ“š Documentation" },
  { field = "remote.pr_title", pattern = "perf:", group = "<!-- 4 -->âš¡ Performance" },
  { field = "remote.pr_title", pattern = "refactor:", group = "<!-- 2 -->ğŸšœ Refactor" },
  { field = "remote.pr_title", pattern = "style:", group = "<!-- 5 -->ğŸ¨ Styling" },
  { field = "remote.pr_title", pattern = "test:", group = "<!-- 6 -->ğŸ§ª Testing" },
  { field = "remote.pr_title", pattern = "chore\\(release\\):", skip = true },
  { field = "remote.pr_title", pattern = "chore\\(deps.*\\):", skip = true },
  { field = "remote.pr_title", pattern = "chore\\(pr\\):", skip = true },
  { field = "remote.pr_title", pattern = "chore\\(pull\\):", skip = true },
  { field = "remote.pr_title", pattern = "chore:|ci:", group = "<!-- 7 -->âš™ï¸ Miscellaneous Tasks" },
  { field = "remote.pr_title", pattern = "revert:", group = "<!-- 9 -->â—€ï¸ Revert" },
  { field = "remote.pr_title", pattern = ".*", group = "<!-- 10 -->ğŸ’¼ Other" },
]
protect_breaking_commits = false
filter_commits = true
topo_order = false
sort_commits = "oldest"
